apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - agent-config.yaml
  - validator-origin-statefulset.yaml
  - validator-origin-secret.yaml
  - validator-target-statefulset.yaml
  - validator-target-secret.yaml
  - relayer-statefulset.yaml
  - relayer-secret.yaml
  - relayer-service.yaml
  - relayer-ingress.yaml
