apiVersion: v1
kind: Service
metadata:
  name: hyperlane-relayer
  namespace: hyperlane
  labels:
    app: hyperlane-relayer
spec:
  type: ClusterIP
  selector:
    app: hyperlane-relayer
  ports:
    - name: metrics
      port: 9091
      targetPort: 9091
      protocol: TCP
    - name: http
      port: 80
      targetPort: 9090
      protocol: TCP
