apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hyperlane-relayer-secrets
  namespace: hyperlane
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: hyperlane-relayer-secrets
    creationPolicy: Owner
  data:
    - secretKey: target_chain_signer_key
      remoteRef:
        key: /unmanaged/secrets/hyperlane/bullet_signer_key
    - secretKey: origin_chain_signer_key
      remoteRef:
        key: /unmanaged/secrets/hyperlane/solana_signer_key
    - secretKey: origin_chain_rpc_url
      remoteRef:
        key: /unmanaged/secrets/hyperlane/relayer_rpc
