apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hyperlane-validator-bullettestnet-secrets
  namespace: hyperlane
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: hyperlane-validator-bullettestnet-secrets
    creationPolicy: Owner
  data:
    - secretKey: hyperlane_validator_signer_key
      remoteRef:
        key: /unmanaged/secrets/hyperlane/validator_signer_key
    - secretKey: origin_chain_signer_key
      remoteRef:
        key: /unmanaged/secrets/hyperlane/bullet_signer_key
